### ISSUE TITLE
nctelegram freeze at startup

### ISSUE THREAD

**Issue by Quadronick** [Nanoseb/ncTelegram#11]
Hi

nctelegram on Arch. Builded today. Nctelegram freeze at start. Just empty output. If i press Ctl+C it hows traceback i pasted below...

^CTraceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 32, in get_new_chan_list
    self.chans = self.Telegram_ui.sender.dialog_list()
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, _args, *_kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 351, in execute_function
    return result_parser(message)
  File "/usr/lib/python3.5/site-packages/pytg/result_parser.py", line 105, in **call**
    raise IllegalResponseException("Not a list: {json}".format(json=str(json)))
pytg.exceptions.IllegalResponseException: Not a list: {'error': 'RPC_CALL_FAIL 401: AUTH_KEY_UNREGISTERED', 'result': 'FAIL', 'error_code': 71}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 79, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.5/site-packages/ncTelegram/**init**.py", line 63, in **init**
    self.chan_widget = ChanWidget(self)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 21, in **init**
    self.get_new_chan_list()
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 35, in get_new_chan_list
    time.sleep(0.5)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1700, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
read: Connection reset by peer

**Comment by Nanoseb** [comment]
Hi,
Is it working better now ?
Have you ran `telegram-cli` first ?
I can't really fix that one, if `telegram-cli` works then the error appears between `pytg` and `telagram-cli`

**Comment by Nanoseb** [comment]
I am closing that one, feel free to reopen it if needed.

**Comment by Quadronick** [comment]
Sorry for the long silence. Everything works fine thank you. Just always forget to answer here. Too much work to do.
