### ISSUE TITLE
Cannot run nctelegram

### ISSUE THREAD

**Issue by gamehelp16** [Nanoseb/ncTelegram#13]
```
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 70, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.5/site-packages/ncTelegram/__init__.py", line 62, in __init__
    self.chan_widget = ChanWidget(self)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 21, in __init__
    self.get_new_chan_list()
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 41, in get_new_chan_list
    cmd = chan['type'] + "#" + str(chan['id'])
KeyError: 'type'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/subprocess.py", line 1068, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.5/subprocess.py", line 1687, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
read: Connection reset by peer
```

**Comment by Nanoseb** [comment]
sorry for the delay, do you still have this issue? 
if yes can you give me some context, when does this happens?

**Comment by gamehelp16** [comment]
This happens when launching the app using terminal (`nctelegram`)

**Comment by ElectroCamel** [comment]
Same here, Arch Linux.

It hangs when launching `nctelegram`, and when stopped by ctrl-C, i get: 

`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_chanwidget.py", line 32, in get_new_chan_list
    self.chans = self.Telegram_ui.sender.dialog_list()
  File "/usr/lib/python3.6/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pytg/sender.py", line 351, in execute_function
    return result_parser(message)
  File "/usr/lib/python3.6/site-packages/pytg/result_parser.py", line 105, in __call__
    raise IllegalResponseException("Not a list: {json}".format(json=str(json)))
pytg.exceptions.IllegalResponseException: Not a list: {'result': 'FAIL', 'error_code': 71, 'error': 'RPC_CALL_FAIL 401: AUTH_KEY_UNREGISTERED'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 80, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.6/site-packages/ncTelegram/__init__.py", line 63, in __init__
    self.chan_widget = ChanWidget(self)
  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_chanwidget.py", line 21, in __init__
    self.get_new_chan_list()
  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_chanwidget.py", line 35, in get_new_chan_list
    time.sleep(0.5)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 836, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1478, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
read: Resource temporarily unavailable
`

**Comment by Nanoseb** [comment]
@ElectroCamel this is a different error, can you open a new issue

**Comment by ob-ivan** [comment]
I can confirm the same issue as @gamehelp16 faced. I'm on Fedora 26, running `nctelegram` from command line. The output is as follows:

```
Traceback (most recent call last):
  File "/bin/nctelegram", line 70, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.6/site-packages/ncTelegram/__init__.py", line 62, in __init__
    self.chan_widget = ChanWidget(self)
  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_chanwidget.py", line 21, in __init__
    self.get_new_chan_list()
  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_chanwidget.py", line 41, in get_new_chan_list
    cmd = chan['type'] + "#" + str(chan['id'])
KeyError: 'type'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/subprocess.py", line 838, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 1488, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
read: Connection reset by peer
```

The story is a bit complicated. I first installed nctelegram 0.9.1 on previous installation of Fedora 26, then I had to reinstall the OS. I installed it from the same distrib, but when I tried to install nctelegram 0.9.2, the dependencies seem to have upgraded, and I had to upgrade setuptools python package by hand (see https://github.com/pypa/setuptools/issues/1086). After that nctelegram reinstalled smoothly, but now it gives the above error output on start.

What can we do about that? I need telegram for work, and nctelegram is the most fitting client out there. I would hate to switch to any other one.

**Comment by Nanoseb** [comment]
Hi,
What happened if you try to install the very last version:
`sudo pip3 install --upgrade https://github.com/Nanoseb/ncTelegram/archive/master.tar.gz`

When the readme was written, fedora's telegram-cli was at an older stage so only nctelegram below 0.9.2 could work, but I guess they've updated their repos now.

**Comment by ob-ivan** [comment]
> What happened if you try to install the very last version:

Well, it works! Thank you @Nanoseb !

**Comment by Nanoseb** [comment]
Well, that's what you get when you give enough details about an issue.
