### ISSUE TITLE
Cannot start - "Remote end closed" exception

### ISSUE THREAD

**Issue by axel22** [Nanoseb/ncTelegram#34]
I get the following error when running `nctelegram`. This is weird, because it worked yesterday:

```
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.

Traceback (most recent call last):
  File "/usr/local/bin/nctelegram", line 93, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/local/lib/python3.4/dist-packages/ncTelegram/__init__.py", line 73, in __init__
    self.msg_widget = MessageWidget(self)
  File "/usr/local/lib/python3.4/dist-packages/ncTelegram/ui_msgwidget.py", line 25, in __init__
    self.get_history()
  File "/usr/local/lib/python3.4/dist-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history
    self.print_msg(msg)
  File "/usr/local/lib/python3.4/dist-packages/ncTelegram/ui_msgwidget.py", line 141, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/local/lib/python3.4/dist-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/local/lib/python3.4/dist-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
pytg.exceptions.ConnectionError: Remote end closed
```

**Comment by aidenholmes** [comment]
Same exact error here, it worked a few minutes ago, on Ubuntu 18.04
```
⋊> ~ nctelegram
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.

Traceback (most recent call last):
  File "/usr/local/bin/nctelegram", line 93, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/__init__.py", line 73, in __init__
    self.msg_widget = MessageWidget(self)
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/ui_msgwidget.py", line 25, in __init__
    self.get_history()
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history
    self.print_msg(msg)
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/ui_msgwidget.py", line 141, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/local/lib/python3.6/dist-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/local/lib/python3.6/dist-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
pytg.exceptions.ConnectionError: Remote end closed
```

**Comment by cagnulein** [comment]
similar issue here

```
$ nctelegram 
change_user_group: can't find the user telegramd to switch to
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.

Traceback (most recent call last):
  File "/usr/local/bin/nctelegram", line 93, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/__init__.py", line 73, in __init__
    self.msg_widget = MessageWidget(self)
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/ui_msgwidget.py", line 25, in __init__
    self.get_history()
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history
    self.print_msg(msg)
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/ui_msgwidget.py", line 141, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/local/lib/python3.6/dist-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/local/lib/python3.6/dist-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
pytg.exceptions.ConnectionError: Remote end closed

```

**Comment by NateDogg1232** [comment]
Gonna bump this, as this issue still exists.

**Comment by lulivi** [comment]
Also failing for me, with ArchLinux (5.3.7-arch1-2-ARCH) and Python 3.7.4. Same error: `pytg.exceptions.ConnectionError: Remote end closed`

**Comment by chrys87** [comment]
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 93, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.7/site-packages/ncTelegram/__init__.py", line 73, in __init__
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/site-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.

    self.msg_widget = MessageWidget(self)
  File "/usr/lib/python3.7/site-packages/ncTelegram/ui_msgwidget.py", line 25, in __init__
    self.get_history()
  File "/usr/lib/python3.7/site-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.7/site-packages/ncTelegram/ui_msgwidget.py", line 141, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/lib/python3.7/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/lib/python3.7/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
pytg.exceptions.ConnectionError: Remote end closed
