### ISSUE TITLE
crashes with `telegram-cli: loop.c:742: accept_incoming: Assertion `fd >= 0' failed.`

### ISSUE THREAD

**Issue by towc** [Nanoseb/ncTelegram#41]
telegram-cli was installed with snap

Here's the traceback:

```
$ nctelegram
telegram-cli: loop.c:742: accept_incoming: Assertion `fd >= 0' failed.
Traceback (most recent call last):
  File "/usr/local/bin/nctelegram", line 93, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/__init__.py", line 39, in __init__
    self.start_Telegram()
  File "/usr/local/lib/python3.6/dist-packages/ncTelegram/__init__.py", line 187, in start_Telegram
    pubkey_file=PATH_PUBKEY)
  File "/usr/local/lib/python3.6/dist-packages/pytg/__init__.py", line 52, in __init__
    raise AssertionError("CLI Process died.")
AssertionError: CLI Process died.
```

I used the ncTelegram.conf from this repo, and modified the first 2 parts like so:

```
$ cat .ncTelegram.conf | head -n 3
[general]
path_telegram = /snap/bin/telegram-cli
path_pubkey = /home/user/tg/server.pub
```
`~/tg` also has `tg-server.pub` in it, and I tried using that too, but I get the exact same traceback

It's curious because the only results to `sudo updatedb && locate server.pub` are the 2 items in `~/tg`, and I don't think that directory comes from snap, but from a failed attempt of me installing telegram-cli, before realizing I could use snap. I can't seem to find those `server.pub` files from the snap install

**Comment by FreedomSka** [comment]
I have the same exact issue, I have checked and my **path_telegram** is in **/usr/bin/telegram-cli** and my **path_pubkey** is in **/etc/telegram-cli/server.pub** (default path for telegram-cli)

you can search them with

`
$ which telegram-cli
/usr/bin/telegram-cli
$ sudo updatedb
$ locate server.pub | grep telegram
/etc/telegram-cli/server.pub
`
