### ISSUE TITLE
pytg.exceptions.ConnectionError: Remote end closed

### ISSUE THREAD

**Issue by matheusfillipe** [Nanoseb/ncTelegram#48]
When trying to open nctelegram on arch:

`
Exception in thread Receiver (pytg):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 93, in <module>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.8/site-packages/ncTelegram/__init__.py", line 73, in __init__
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.msg_widget = MessageWidget(self)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/ncTelegram/ui_msgwidget.py", line 25, in __init__
  File "/usr/lib/python3.8/site-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
    self.get_history()
pytg.exceptions.ConnectionError: Remote end closed.
  File "/usr/lib/python3.8/site-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.8/site-packages/ncTelegram/ui_msgwidget.py", line 141, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/lib/python3.8/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/lib/python3.8/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
pytg.exceptions.ConnectionError: Remote end closed

`

**Comment by privacy313** [comment]
I'm getting the same error on startup. also on arch.
It was working fine yesterday.

`Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 93, in <module>
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/site-packages/ncTelegram/__init__.py", line 73, in __init__
    self._target(*self._args, **self._kwargs)
    self.msg_widget = MessageWidget(self)
  File "/home/privacy313/.local/lib/python3.8/site-packages/pytg/receiver.py", line 125, in _receiver
  File "/usr/lib/python3.8/site-packages/ncTelegram/ui_msgwidget.py", line 25, in __init__
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.
    self.get_history()
  File "/usr/lib/python3.8/site-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.8/site-packages/ncTelegram/ui_msgwidget.py", line 141, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/home/privacy313/.local/lib/python3.8/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/home/privacy313/.local/lib/python3.8/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/home/privacy313/.local/lib/python3.8/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
pytg.exceptions.ConnectionError: Remote end closed`

**Comment by im-deep** [comment]
same exception on fresh install, telegram-cli is set up correctly and not running.

**Comment by diego-rapoport** [comment]
Same problem and also arch.

**Comment by matheusfillipe** [comment]
This project is long unmaintained, I don't know if any fork continued it but I found this nice alternative with vi like bindings: https://github.com/paul-nameless/tg

**Comment by Nanoseb** [comment]
Hi all,
Very sorry for not maintaining this project anymore. As @matheusfillipe mentioned there are some alternatives nowadays and https://github.com/paul-nameless/tg seems like the closest one to what ncTelegram is. So feel free to give that project a shot.
