### ISSUE TITLE
Crash on lookup for some convesations

### ISSUE THREAD

**Issue by Inf1e** [Nanoseb/ncTelegram#49]
infie@chill-arch ~ % nctelegram
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 93, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.8/site-packages/ncTelegram/__init__.py", line 73, in __init__
Exception in thread Receiver (pytg):
Traceback (most recent call last):
    self.msg_widget = MessageWidget(self)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/site-packages/ncTelegram/ui_msgwidget.py", line 25, in __init__
    self.run()
    self.get_history()
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/site-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history
    self.print_msg(msg)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/ncTelegram/ui_msgwidget.py", line 141, in print_msg
  File "/usr/lib/python3.8/site-packages/pytg/receiver.py", line 125, in _receiver
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/lib/python3.8/site-packages/pytg/sender.py", line 630, in command_alias
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/lib/python3.8/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
pytg.exceptions.ConnectionError: Remote end closed

**Comment by afeedh** [comment]
I'm experiencing the same problem.

**Comment by gibranlp** [comment]
i believe im having the same issue

```
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 93, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.9/site-packages/ncTelegram/__init__.py", line 91, in __init__
    self.main_loop.run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.9/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3.9/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.9/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.9/site-packages/ncTelegram/ui_chanwidget.py", line 195, in keypress
    key = super(ChanWidget, self).keypress(size, key)
  File "/usr/lib/python3.9/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.9/site-packages/urwid/wimp.py", line 543, in keypress
    self._emit('click')
  File "/usr/lib/python3.9/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.9/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.9/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.9/site-packages/ncTelegram/ui_chanwidget.py", line 177, in chan_change
    self.Telegram_ui.msg_widget.get_history()
  File "/usr/lib/python3.9/site-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.9/site-packages/ncTelegram/ui_msgwidget.py", line 119, in print_msg
    image = self.get_inline_img(msg)
  File "/usr/lib/python3.9/site-packages/ncTelegram/ui_msgwidget.py", line 279, in get_inline_img
    path = self.Telegram_ui.download_media(msg)
  File "/usr/lib/python3.9/site-packages/ncTelegram/__init__.py", line 159, in download_media
    file = self.sender.load_photo(mid)
  File "/usr/lib/python3.9/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pytg/sender.py", line 351, in execute_function
    return result_parser(message)
  File "/usr/lib/python3.9/site-packages/pytg/result_parser.py", line 74, in downloaded_file
    raise IllegalResponseException("Has no valid event attribute.")
pytg.exceptions.IllegalResponseException: Has no valid event attribute.
```
