### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by z1lt0id** [Nanoseb/ncTelegram#8]
This evening nctelegram just stopped working, here is the output I received. Tries to load and then crashes straight away.
```
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 79, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.5/site-packages/ncTelegram/__init__.py", line 69, in __init__
    self.msg_widget = MessageWidget(self)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 23, in __init__
    self.get_history()
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 51, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 120, in print_msg
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.

    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
pytg.exceptions.ConnectionError: Remote end closed
```

**Comment by z1lt0id** [comment]
Also just to add, I also tried deleting the telegram-cli confs and starting again. I got slightly furthur until I select a chat room I frequent. It crashed and then got this output.
```
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 79, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.5/site-packages/ncTelegram/__init__.py", line 87, in __init__
    self.main_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.

    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 194, in keypress
    key = super(ChanWidget, self).keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3.5/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 176, in chan_change
    self.Telegram_ui.msg_widget.get_history()
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 51, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 120, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
```

**Comment by z1lt0id** [comment]
Also just to add, I also tried deleting the telegram-cli confs and starting again. I got slightly furthur until I select a chat room I frequent. It crashed and then got this output.
```
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 79, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.5/site-packages/ncTelegram/__init__.py", line 87, in __init__
    self.main_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.

    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 194, in keypress
    key = super(ChanWidget, self).keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3.5/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 176, in chan_change
    self.Telegram_ui.msg_widget.get_history()
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 51, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 120, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
```

**Comment by z1lt0id** [comment]
Also just to add, I also tried deleting the telegram-cli confs and starting again. I got slightly furthur until I select a chat room I frequent. It crashed and then got this output.
```
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 79, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.5/site-packages/ncTelegram/__init__.py", line 87, in __init__
    self.main_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.

    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 194, in keypress
    key = super(ChanWidget, self).keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3.5/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 176, in chan_change
    self.Telegram_ui.msg_widget.get_history()
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 51, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 120, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
```

**Comment by z1lt0id** [comment]
Also just to add, I also tried deleting the telegram-cli confs and starting again. I got slightly furthur until I select a chat room I frequent. It crashed and then got this output.
```
Traceback (most recent call last):
  File "/usr/bin/nctelegram", line 79, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.5/site-packages/ncTelegram/__init__.py", line 87, in __init__
    self.main_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/receiver.py", line 125, in _receiver
    raise ConnectionError("Remote end closed.")
pytg.exceptions.ConnectionError: Remote end closed.

    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 194, in keypress
    key = super(ChanWidget, self).keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3.5/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_chanwidget.py", line 176, in chan_change
    self.Telegram_ui.msg_widget.get_history()
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 51, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.5/site-packages/ncTelegram/ui_msgwidget.py", line 120, in print_msg
    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/usr/lib/python3.5/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
```

**Comment by Nanoseb** [comment]
I managed to recreate this error, it appends when someone reply to a message and the first message is deleted. Unfortunately I can't fix this because the simple fact of querying for a deleted message makes telegram-cli to crash (and there is no way of knowing if a message have been deleted). The only way to bypass this error is to delete the reply.
If you want you can report this to telegram-cli (but it is not actively developed).

**Comment by z1lt0id** [comment]
Ahh thanks for that. It did start working again eventually - but good to know.
